package visao;

import dao.pessoa.PessoaDAO;
import dao.pessoa.PessoaDAOMySQL;
import modelo.Pessoa;

public class FrmCadastroPessoa extends javax.swing.JFrame {

    public FrmCadastroPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFIdade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFDataNascimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JBTSair = new javax.swing.JButton();
        JBTLimpar = new javax.swing.JButton();
        jBTSalvar = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        JBTAlterar = new javax.swing.JButton();
        JBTListar = new javax.swing.JButton();
        jRBCasado = new javax.swing.JRadioButton();
        jRBSolteiro = new javax.swing.JRadioButton();
        jRBViuvo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Dados de Pessoa");

        jLabel2.setText("Nome:");

        jTFNome.setName("JTFNome"); // NOI18N

        jTFIdade.setName("JTFNome"); // NOI18N

        jLabel3.setText("Idade:");

        jLabel4.setText("Data Nascimento:");

        jTFDataNascimento.setName("JTFNome"); // NOI18N

        jLabel5.setText("Cidade:");

        jTFCidade.setName("JTFNome"); // NOI18N

        jLabel6.setText("Estado Civil:");

        JBTSair.setText("Sair");
        JBTSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTSairActionPerformed(evt);
            }
        });

        JBTLimpar.setText("Limpar");
        JBTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTLimparActionPerformed(evt);
            }
        });

        jBTSalvar.setText("Salvar");
        jBTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalvarActionPerformed(evt);
            }
        });

        jBTExcluir.setText("Excluir");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        JBTAlterar.setText("Alterar");
        JBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTAlterarActionPerformed(evt);
            }
        });

        JBTListar.setText("Listar");
        JBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTListarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBCasado);
        jRBCasado.setText("Casado");

        buttonGroup1.add(jRBSolteiro);
        jRBSolteiro.setText("Solteiro");

        buttonGroup1.add(jRBViuvo);
        jRBViuvo.setText("Viúvo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jTFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBTAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTListar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBTLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBViuvo)
                            .addComponent(jRBSolteiro)
                            .addComponent(jRBCasado)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBTAlterar, JBTLimpar, JBTListar, JBTSair, jBTExcluir, jBTSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jBTSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBTListar)
                        .addGap(5, 5, 5))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBTAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jTFIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(jTFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBCasado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBSolteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBViuvo)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBTSairActionPerformed

    private void JBTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTLimparActionPerformed
        jTFNome.setText("");
        jTFIdade.setText("");
        jTFDataNascimento.setText("");
        jTFCidade.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_JBTLimparActionPerformed

    private void jBTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalvarActionPerformed
        if (!jTFNome.getText().equals("")) {
            Pessoa pessoa = new Pessoa();
            if (pessoaId != -1) {
                pessoa.setPessoaId(pessoaId);
            }
            pessoa.setNome(jTFNome.getText());
            pessoa.setIdade(jTFIdade.getText());
            pessoa.setDataNascimento(jTFDataNascimento.getText());
            pessoa.setCidade(jTFCidade.getText());

            if (jRBCasado.isSelected()) {
                pessoa.setEstadoCivil("Casado");
            } else if (jRBSolteiro.isSelected()) {
                pessoa.setEstadoCivil("Solteiro");
            } else if (jRBViuvo.isSelected()) {
                pessoa.setEstadoCivil("Viuvo");
            } else {
                buttonGroup1.clearSelection();
            }
            PessoaDAO pessoadao = new PessoaDAOMySQL();
            if (pessoadao.salvar(pessoa)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Pessoa cadastrado com suscesso!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Pessoa não cadastrado!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "O Nome deve ser preenchido!");
            jTFNome.requestFocus();
        }
    }//GEN-LAST:event_jBTSalvarActionPerformed

    private void JBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTListarActionPerformed
        //this.setVisible(false);
        new FrmPessoaListar().setVisible(true);
    }//GEN-LAST:event_JBTListarActionPerformed

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        String id = javax.swing.JOptionPane.showInputDialog("Digite o id a ser excluído");
        PessoaDAO pessoadao = new PessoaDAOMySQL();
        Pessoa pessoa = pessoadao.consultarPK(id);
        if (pessoa != null) {
            jTFNome.setText(pessoa.getNome());
            jTFIdade.setText(pessoa.getIdade());
            jTFDataNascimento.setText(pessoa.getDataNascimento());
            jTFCidade.setText(pessoa.getCidade());
            if (pessoa.getEstadoCivil().equalsIgnoreCase("Casado")) {
                jRBCasado.setSelected(true);
                jRBSolteiro.setSelected(false);
                jRBViuvo.setSelected(false);
            } else if (pessoa.getEstadoCivil().equalsIgnoreCase("Solteiro")) {
                jRBCasado.setSelected(false);
                jRBSolteiro.setSelected(true);
                jRBViuvo.setSelected(false);
            } else if (pessoa.getEstadoCivil().equalsIgnoreCase("Viuvo")) {
                jRBCasado.setSelected(false);
                jRBSolteiro.setSelected(false);
                jRBViuvo.setSelected(true);
            } else {
                buttonGroup1.clearSelection();
            }

            Object[] opcoes = {"Sim", "Não"};
            int resposta = javax.swing.JOptionPane.showOptionDialog(null, "Confirma a exclusão do Pessoa?", "Exclusão", 0, javax.swing.JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);
            if (resposta == 0) {
                if (pessoadao.apagarPK(Integer.parseInt(id))) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Pessoa excluído com suscesso!");
                    jTFNome.setText("");
                    jTFIdade.setText("");
                    jTFDataNascimento.setText("");
                    jTFCidade.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Pessoa não excluído!");
                }
            }
        }
    }//GEN-LAST:event_jBTExcluirActionPerformed

    private void JBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTAlterarActionPerformed
        String id = javax.swing.JOptionPane.showInputDialog("Digite o id a ser alterado");
        PessoaDAO pessoadao = new PessoaDAOMySQL();
        Pessoa pessoa = pessoadao.consultarPK(id);
        if (pessoa != null) {
            pessoaId = pessoa.getPessoaId();
            jTFNome.setText(pessoa.getNome());
            jTFIdade.setText(pessoa.getIdade());
            jTFDataNascimento.setText(pessoa.getDataNascimento());
            jTFCidade.setText(pessoa.getCidade());
            if (pessoa.getEstadoCivil().equalsIgnoreCase("Casado")) {
                jRBCasado.setSelected(true);
                jRBSolteiro.setSelected(false);
                jRBViuvo.setSelected(false);
            } else if (pessoa.getEstadoCivil().equalsIgnoreCase("Solteiro")) {
                jRBCasado.setSelected(false);
                jRBSolteiro.setSelected(true);
                jRBViuvo.setSelected(false);
            } else if (pessoa.getEstadoCivil().equalsIgnoreCase("Viuvo")) {
                jRBCasado.setSelected(false);
                jRBSolteiro.setSelected(false);
                jRBViuvo.setSelected(true);
            } else {
                jRBCasado.setSelected(false);
                jRBSolteiro.setSelected(false);
                jRBViuvo.setSelected(false);
            }
        }
    }//GEN-LAST:event_JBTAlterarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroPessoa().setVisible(true);
            }
        });
    }
    private int pessoaId = -1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTAlterar;
    private javax.swing.JButton JBTLimpar;
    private javax.swing.JButton JBTListar;
    private javax.swing.JButton JBTSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRBCasado;
    private javax.swing.JRadioButton jRBSolteiro;
    private javax.swing.JRadioButton jRBViuvo;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFDataNascimento;
    private javax.swing.JTextField jTFIdade;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
